language: cpp
dist: trusty
sudo: required
services: [ docker ]
git: { depth: 3 }
os: linux
compiler: gcc

env:
  global:
    - QT_SELECT=qt5
  matrix:
    - OS=ubuntu DIST=xenial
    - OS=ubuntu DIST=zesty

#matrix:
#  include: # add non-linux targets
#    - os: osx
#      env: QT_SELECT=qt5
#      compiler: gcc

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then mkdir docker; DOCKER=docker/Dockerfile; echo FROM $OS:$DIST >$DOCKER; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then echo "RUN apt-get update && apt-get install -y build-essential qtbase5-dev zlib1g-dev debhelper" >>$DOCKER; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then docker build -f $DOCKER docker -t build_env; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install qt5; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew link qt5 --force; fi

before_script:
  - if [ $TRAVIS_OS_NAME = linux ]; then sed -i "1s/zesty;/$DIST;/" debian/changelog; touch -r debian/control debian/changelog; ls -l debian; fi
  
script:
  - if [ $TRAVIS_OS_NAME = linux ]; then docker run -it -w /${TRAVIS_REPO_SLUG#*/} -e QT_SELECT -v $PWD:/${TRAVIS_REPO_SLUG#*/} build_env dpkg-buildpackage -us -uc -nc; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then qmake; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then make; fi

after_script:
  - ls -lR

# Set encrypted variable 'api_key' in Travis repo settings to deploy packages
# for tagged commits to GitHub Releases.
# Set encrypted variable 'PACKAGECLOUD_TOKEN' in Travis repo settings to deploy packages
# for tagged commits to packagecloud repo.
deploy:
  - provider: releases
    api_key: ${api_key}
    file_glob: true
    file: $TRAVIS_BUILD_DIR/*.dmg
    skip_cleanup: true
    on:
        # Deploy only when tag is specified
        tags: true
        # and only packages generated for osx
        # and only when API token is set
        condition: "$TRAVIS_OS_NAME = osx && ${#api_key} != 0"
  - provider: packagecloud
    repository: ${TRAVIS_REPO_SLUG#*/}
    username: ${TRAVIS_REPO_SLUG%/*}
    token: $PACKAGECLOUD_TOKEN
    dist: $OS/$DIST
    package_glob: $TRAVIS_BUILD_DIR/*.{deb,rpm}
    skip_cleanup: true
    on:
        # Deploy only when tag is specified
        tags: true
        # and only packages generated for linux
        # and only when API token is set
condition: "$TRAVIS_OS_NAME = linux && ${#PACKAGECLOUD_TOKEN} != 0"
